### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by yurisuika** [Minenash/TinyConfig#1]
Hi,

First off I'd like to say thanks for making this! It has really helped kickstart my first use of configs.

I am running into one issue though. That being that there is no scrolling ability for the overflow.

I've been looking at other classes to see how they implement scrollbars but I've yet to figure it out myself.

Thank you!

**Comment by Minenash** [comment]
Ah, this finally caught up to me. I actually had a mod for awhile where there was a "bug" that one setting didn't have it's own toggle, but was attached to a different one, and somehow no one noticed.

If you're looking for scrolling (and some other features), I'd recommend using MidnightConfig, they removed tooltips (what was a huge amount of the size in mine), but added a bunch of other stuff while still being quite small

**Comment by yurisuika** [comment]
Thank you for the recommendation, I'll try it out!
